proxy:
  title: ProteinCleaver Application
  hide-navbar: true
  logo-url: https://www.openanalytics.eu/shinyproxy/logo.png
  landing-page: /app/Proteincleaver
  heartbeat-rate: 10000
  heartbeat-timeout: 60000
  container-wait-time: 60000
  port: 80
  authentication: none
  
  # Docker configuration
  docker:
    url: http://localhost:2375
    port-range-start: 20000
  specs:
  - id: Proteincleaver
    display-name: ProteinCleaver Application
    description: Application which demonstrates ProteinCleaver
    container-cmd: ["R", "-e", "shiny::runApp('/root/app/src')"]
    container-image: fiver-app:1.1
    
logging:
  file:
    name: shinyproxy.log
management:
    server:
        port: 9090


